### ISSUE TITLE
你好，请问博客用的什么程序？

### ISSUE THREAD

**Issue by Cregin** [niyaoyao/niyaoyao.github.io#1]
😀

**Comment by niyaoyao** [comment]
@lzyroot Hi, I use hexo cli to deply my static blog pages.
 You can go to https://hexo.io for more information.

**Comment by Cregin** [comment]
请问用的哪个主题呢，很棒

**Comment by niyaoyao** [comment]
Sorry for reply late, you can find theme at https://github.com/forsigner/fexo
